### ISSUE TITLE
Use NSError to relay status codes

### ISSUE THREAD

**Issue by powerje** [CodaFi/AFNetworking-RACExtensions#40]
I like that now the JSON and HTTPResponse objects come back in a RACTuple in `sendNext` but often I want to know the status code in `sendError` as well. My solution to this is to replace the 'code' of the NSError sent through with the http status code of the failing request.

I made a similar change to Moya in https://github.com/ashfurrow/Moya/pull/50, would a change like that be welcome here?

**Comment by CodaFi** [comment]
Are client side errors really that trivial that you would replace them like this?

**Comment by powerje** [comment]
That's a good point. Perhaps instead of replacing the code of the NSError the response could be added to the NSError dictionary, or at least the failing status code?

**Comment by CodaFi** [comment]
Mm, yeah. Any key you would suggest they be put under?

**Comment by powerje** [comment]
I think just `response` would be fine?

**Comment by CodaFi** [comment]
I mean in the error dictionary?

**Comment by powerje** [comment]
Sorry, yes I was thinking we could add 'response' as a key in the error dictionary and the response object as its value?

**Comment by rayshih** [comment]
I am now facing this needs. Our server API response some error information in the body of http. And our app needs to handle the error base on the body. Since we're in hurry so I'll fork one.

**Comment by CodaFi** [comment]
Fixed by the merge of #41.

**Comment by powerje** [comment]
Thanks, glad to see this in here!

Sorry @CodaFi I would've sent a PR myself but I wasn't sure if we were settled on how you would like to have it done.

**Comment by rayshih** [comment]
I have a question: How to run and write a test for this extension? 

Since I couldn't even do `pod install` by this extension only, I just used our project as a test environment.

**Comment by CodaFi** [comment]
We could bump the CP spec version or you could just use submodules.

**Comment by rayshih** [comment]
Could you push new version to pod spec? I'll very appreciate your help.

**Comment by CodaFi** [comment]
Does the latest commit do it for you?

**Comment by rayshih** [comment]
It still show only up to 0.1.6 when I use `pod search AFNetworking-RACExtensions`

and the CocoaPods/Spec repo show the same thing.
https://github.com/CocoaPods/Specs/tree/master/Specs/AFNetworking-RACExtensions

**Comment by powerje** [comment]
@rayshih @CodaFi thanks for your work on this!

I'm working on updating my app to use the latest version of this library and just realized that while this change gives the responseObject I don't think it gives the http status code within the NSError. Am I wrong about that / is there a way to get the status code? If not, would a pull request to add that be welcome?

**Comment by CodaFi** [comment]
Good God, this reeks of specification creep.  But if you can manage it in a minimal way, I will merge it.
