### ISSUE TITLE
Version 0.1.8 is not published on CocoaPods trunck

### ISSUE THREAD

**Issue by guidomb** [CodaFi/AFNetworking-RACExtensions#42]
```
[!] Unable to satisfy the following requirements:

- `AFNetworking-RACExtensions (~> 0.1.8)` required by `Podfile`
```

**Comment by KevinVitale** [comment]
I'd like to second this. Publishing the last version would be very helpful. Thanks.

**Comment by CodaFi** [comment]
This issue and #35 are duplicates.

@kastiglione Shall we give the people what they want?

**Comment by rayshih** [comment]
Oh please

**Comment by KevinVitale** [comment]
Any updates on this?

**Comment by iamdaiyuan** [comment]
I pull request, update to 0.1.8
https://github.com/CocoaPods/Specs/pull/13061

**Comment by k** [comment]
Um has anyone claimed this pod?

**Comment by chiahsien** [comment]
For those who needs 0.1.8, add this to your Podfile

```
pod 'AFNetworking-RACExtensions', :git => 'https://github.com/CodaFi/AFNetworking-RACExtensions.git', :commit => '108d9bdf08a644c754e48f4a4896f7a23841dce7'
```

Q: Why can't I use `:tag => '0.1.8'`?
A: Because the podspec file under tag `0.1.8` points to tag `0.1.6`.

Q: Why do I need to specify the `:commit`?
A: Because podspec got updated and points to tag `0.1.8` in this commit.

Q: What if I don't specify the `:commit`?
A: Then you will get the latest `master`, which may be or may not be what you want.

**Comment by chiahsien** [comment]
Ping @kastiglione @tonyarnold, please help.
Or, can you add me as a contributor? I can help in the future.
http://guides.cocoapods.org/making/getting-setup-with-trunk#adding-other-people-as-contributors

**Comment by kastiglione** [comment]
@chiahsien I'm not an admin here. Why not open a pull request?

**Comment by chiahsien** [comment]
@kastiglione
Cocoapods doesn't accept pull request for newer podspec anymore. 
The only way to submit podspec is to use `pod trunk`.

**Comment by chiahsien** [comment]
You can see my previous life link for more information about `pod trunk`.

**Comment by KevinVitale** [comment]
@chiahsien:
> "For those who needs 0.1.8, add this to your Podfile..."

Thanks for the tip. In my case, this pod is a dependency on an internal development pod; I don't want to have to fork the spec repo just for this, nor do I want my team to have to manage that burden.

Getting the spec updated is still really important to us, though.

**Comment by kastiglione** [comment]
@chiahsien I'm not an admin of this project. I'm not an owner/admin of the podspec. I don't know if there's anything I can do for you.

**Comment by CodaFi** [comment]
@kastiglione I don't remember signing up as an admin either, so that leaves @tonyarnold

**Comment by tonyarnold** [comment]
If someone else wants to claim the pod, go for it — no offense intended to @CodaFi but I haven't used this library in a long time. I wouldn't be testing it properly even if I did put the podspec together.

**Comment by chiahsien** [comment]
@CodaFi Maybe you are the owner even though you didn't sign up?
Can you try to claim it then add me to the contributor list?
http://guides.cocoapods.org/making/getting-setup-with-trunk#claiming-an-existing-library

**Comment by CodaFi** [comment]
Well I'll be damned.  I am an admin, apparently.  I'll remove you (or remove yourself) from the list then @tonyarnold, I completely understand where you're coming from.  Thanks for taking the time that you did maintaining this crazy thing.

**Comment by CodaFi** [comment]
@chiahsien Do you have an email you would like me to use to add you to the contributors list?

**Comment by chiahsien** [comment]
@CodaFi chiahsien AT gmail.com, thank you!

**Comment by CodaFi** [comment]
I've just pushed 0.1.8 to the trunk.

I really can't apologize enough for the delay.

**Comment by CodaFi** [comment]
@chiahsien Done!

**Comment by CodaFi** [comment]
@chiahsien I'm going to remove that comment to keep your email private.

**Comment by chiahsien** [comment]
Thank you all for your efforts!
